### ISSUE TITLE
Notification visibility on iOS

### ISSUE THREAD

**Issue by katiefenn** [canonical-ols/javan-rhino#103]
Vanilla style notifications, used for global success and error messages in My Ubuntu, are pinned to the top of the viewport using the `position: fixed;` CSS property value. The visibility of elements with fixed positioning on iOS is affected by screen zooming on mobile, and as such important notifications may not be seen by the user.

**Comment by earnubs** [comment]
Only issue in fixed position notifications, which we don't use anymore.
