### ISSUE TITLE
Cannot add card details (production)

### ISSUE THREAD

**Issue by cprov** [canonical-ols/javan-rhino#156]
Despite all form fields looking green, I get the following message on top of the page, when trying to add my card details:

`Error: There's been a problem adding your card. Please verify that card details you provided are correct or use a different card and try again.Dismiss`

Would Stripe provide any additional information on why it is not working ?

Shall the application provide a 'Contact Us' link ?

**Comment by earnubs** [comment]
Hi Celso, the SCA API isn't expressive enough right now to tell us more, the CLI also needs more detail here I believe. It's a post sprint item for SCA I understand.

Also, prod doesn't have the right key ATM.

If you can tell me where you think the contact link should go I will add it.

**Comment by cprov** [comment]
Thanks, Stephen.

I was thinking of a 'Contact us' link for situations we can't provide enough information to move the user forward. It looks like, for this specific case, we can explore Stripe API a bit further and fix production configuration.

However, I am sure there will be genuine errors completely blocking users where we could use a message along the lines of "... If you don't understand why it is happening, please *contact us*."

**Comment by earnubs** [comment]
I have in the past tried to find the answer to where such an email should be sent and come up empty, you might do better :)

**Comment by earnubs** [comment]
Closed because the original bug description is falsey.
