### ISSUE TITLE
Using `dangerouslySetInnerHTML` in Html component because of Helmet

### ISSUE THREAD

**Issue by bartaz** [canonical-ols/javan-rhino#16]
As mentioned in comments to #13, we are using `dangerouslySetInnerHTML` in Html component to set contents of the template (it's based on  [react-redux-universal-hot-example](https://github.com/erikras/react-redux-universal-hot-example/blob/master/src/helpers/Html.js)).

Because usage of `dangerouslySetInnerHTML` seems a bit dirty (even in theoretically safe server side environment) we want to remove it, but in current state it seems to be needed for [Helmet](https://github.com/nfl/react-helmet#server-usage).

If we get rid of calling `renderToString` on content and for example use `children` (as attempted in #15) we case Helmet not to render properly on server side.

So in current state it seems that we need to use `renderToString` and  `dangerouslySetInnerHTML` if we want to keep Helmet.

**Comment by earnubs** [comment]
As @katiefenn pointed out we don't actually need Helmet right now, and it's only there as a "hey, look at this cool thing I found" so I am +1 to remove Helmet until we can prove we need it.

**Comment by bartaz** [comment]
![](http://www.watchstarwars.com/wp-content/uploads/2015/04/helmetoff.gif)

**Comment by bartaz** [comment]
Using `renderToString` and `dangerouslySetInnerHTML` on server side makes sure the same part of React app is rendered both on client and server (react-root matches, so client can reused pre-rendered markup).

Any attempt to fully render Html with app as child component ends up in warning on client:

```
Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering.
```

**Comment by bartaz** [comment]
As discussed with @earnubs and @katiefenn on IRC, having leant that we decided to keep Helmet and `dangerouslySetInnerHTML` as it is.
