### ISSUE TITLE
Error message shown even after success

### ISSUE THREAD

**Issue by Roadmaster** [canonical-ols/javan-rhino#164]
Pete Woods added a fake card (424242424242424... that one). His first attempt failed for reasons not yet determined 

Error: There's been a problem adding your card. Please verify that card details you provided are correct or use a different card and try again.Dismiss

His second attempt succeeded, but the error message still shows at the top of the application window.

http://people.canonical.com/~pete/store_error.png

**Comment by earnubs** [comment]
Fixed in #172
