### ISSUE TITLE
"Postcode" field is labelled incorrectly

### ISSUE THREAD

**Issue by katiefenn** [canonical-ols/javan-rhino#168]
"Postcode" is incorrectly labelled "Phone number":

<img width="511" alt="screen shot 2016-10-20 at 14 39 11" src="https://cloud.githubusercontent.com/assets/1410204/19560054/1dc9d334-96d3-11e6-8e13-b549fe4e51d4.png">

**Comment by bartaz** [comment]
Fixed in #169
