### ISSUE TITLE
when clicking the accept button, sometimes all fields become marked invalid

### ISSUE THREAD

**Issue by pete-woods** [canonical-ols/javan-rhino#176]
As per the title: when filling in the payment details sometimes when you check the TOS box, all fields get a red outline to show they are invalid, even though they already validated and went green.

Browser used was Chromium on 16.04 64-bit VMware machine. I am also using the browser's auto complete functionality for the address.

**Comment by bartaz** [comment]
Seems to be happening when stripe.js is not loaded properly, so validation throws errors when trying to use Stripe validation API.

**Comment by bartaz** [comment]
Seems to be an issue with Helmet. Sometimes Helmet doesn't properly render contents of `<head>`. In these cases (quite random, only happens on some requests) title and head is empty.
Most notably, what is missing is reference to stripe.js script.

```html
<head data-reactid="2"><title data-react-helmet="true" data-reactid="3"></title><link rel="stylesheet" href="/static/style.css" data-reactid="4"/></head>
```

Proper rendered `<head>` should contain title, meta description and link to stripe.js script:

```html
<head data-reactid="2"><title data-react-helmet="true" data-reactid="3">my.ubuntu.com - buy [snap-name]</title><meta data-react-helmet="true" name="description" content="my.ubuntu.com payments ui" data-reactid="4"/><script data-react-helmet="true" src="https://js.stripe.com/v2/" data-reactid="5"></script><link rel="stylesheet" href="/static/style.css" data-reactid="6"/></head>
```

We can workaround it by adding stripe.js as a static link in HTML, but it clearly seems there is some issue with Helmet that we need to debug.

**Comment by bartaz** [comment]
Tried to reproduce it locally (only seen it on staging before).

It seems that it happens to the first request hitting the server (seen it both when running local prod or dev servers). First request gets empty head (no data rendered from Helmet), all the subsequent requests are fine (need to restart the server to see it again).
