### ISSUE TITLE
Enzyme / React / React-Addons-Test-Utils breaking build

### ISSUE THREAD

**Issue by katiefenn** [canonical-ols/javan-rhino#203]
```
"react-addons-test-utils is an implicit dependency in order to support react@0.13-14. Please add the appropriate version to your devDependencies. See https://github.com/airbnb/enzyme#installation"
```

It turns out that Facebook pushed an update to React core and React-Addons-Test-Utils. These packages update in lock-step, as they are sourced from the same code repository. We shrinkwrap React, but we do not shrinkwrap React-Addons-Test-Utils. This meant the latter was free to update when the former did not, causing the peer dependency issue.

**Comment by bartaz** [comment]
Fixed by #206
