### ISSUE TITLE
Error: Cannot find module 'react-dom/lib/ReactTestUtils'

### ISSUE THREAD

**Issue by bartaz** [canonical-ols/javan-rhino#205]
Builds are failing due to some dependency issue in react-addons-test-utils.

**Comment by bartaz** [comment]
Related: https://github.com/airbnb/enzyme/issues/684

**Comment by zhoulujun** [comment]
https://www.zhoulujun.cn/html/tools/webpack/2016_0217_6459.html
  "react": "^16.7.0",
    "react-addons-test-utils": "^15.6.2",
    "react-dom": "^16.7.0",
react-dom 16 根本就没有lib/ReactTestUtils 这玩意儿。
于是修改，react-addons-test-utils index 文件,坑还是未填好
//module.exports = require('react-dom/lib/ReactTestUtils');
module.exports = require('react-dom/test-utils');
最好还是降级到15.x ，期待官方修复！
