### ISSUE TITLE
Server requires dev dependencies when running on prod

### ISSUE THREAD

**Issue by bartaz** [canonical-ols/javan-rhino#217]
https://github.com/canonical-ols/javan-rhino/blob/master/src/server/index.js#L3-L8

Our server requires couple of dev dependencies even when running on prod.
This means it will not run when dev dependencies are not installed.

If these are not needed in production environment, we should probably wrap them in NODE_ENV !== 'production' in this file.
If they are needed in prod (for example to build in production) we need to move them (and many more build dependencies out of devDependencies).

**Comment by earnubs** [comment]
lines 6-8 will be needed in prod, but perhaps they could be written better to take advantage of dead code elimination? ie. If NODE_ENV is production, we don't need to require conf here (the path is just /static/icons)?

**Comment by bartaz** [comment]
Another suspect `chokidar`.
We shouldn't be moving it to prod dependencies as it installs fsevents that may cause us trouble again when installing on Ubuntu.

https://github.com/canonical-ols/javan-rhino/blob/master/src/server/server.js#L7

**Comment by katiefenn** [comment]
These changes work for me with `npm install && npm run build && npm install --production`:

https://github.com/canonical-ols/javan-rhino/compare/build-fix?expand=1

**Comment by bartaz** [comment]
Fixed in #226
