### ISSUE TITLE
Webpack not finding CSS assests after they are moved/renamed

### ISSUE THREAD

**Issue by bartaz** [canonical-ols/javan-rhino#27]
There is some issue with webpack not being able to find CSS file (module) once it was moved or renamed:

```
[webpack-isomorphic-tools] [error] asset not found: ./src/components/navlink/navlink.css
```

This may be caused by fact that asset paths are stored (cached?) in `webpack-assets.json` file.

As a workaround I removed the file and it was recreated by webpack on build.
I don't know if it's a good solution to remove this file before every webpack build or is there some other way.

**Comment by earnubs** [comment]
Don't see this after removing webpackisomorphic tools.
