### ISSUE TITLE
Stripe loaded more than once? 

### ISSUE THREAD

**Issue by earnubs** [canonical-ols/javan-rhino#68]
Navigating from home to payment edit, I see a warning in the console:

```
It looks like Stripe.js was loaded more than one time. Please only load it once per page.
```

**Comment by bartaz** [comment]
I noticed it too on master today.

**Comment by bartaz** [comment]
Seems to be caused by Helmet. For some reason it calls the script (re-renders it in DOM?) every time /payment/edit route is visited (as that's where the script is added with Helmet).

So I guess moving script to Helmet in the App component should help, it will be called and added only once.
